# This is a basic workflow that is manually triggered

name: Server Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deployment:
    runs-on: ubuntu-20.04 # 运行在虚拟机环境 ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm install && npm run deploy
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY_2 }}
          ARGS: "-rltgoDzvO"
          SOURCE: "src/.vuepress/dist"
          REMOTE_HOST: ${{ secrets.SERVER_HOST_2 }}
          REMOTE_USER: ${{ secrets.SERVER_USER_2 }}
          TARGET: "/var/www/shaogefenhao"
